apiVersion: v1
kind: Pod
metadata:
  name: gs-launcher
  labels:
    app: gs-laun
spec:
  containers:
  - image: xiaojunll/gs-launcher
    name: gs-launcher
    ports:
    - containerPort: 9090
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: gs-launcher-service
spec:
  type: NodePort
  ports:
  - port: 9090
    nodePort: 30002
    targetPort: 9090
    protocol: TCP
  selector:
    app: gs-laun